# Description
# # ===========
# # This playbook create an Azure VM with public IP, and open 22 port for SSH
- name: Create Azure VM
  hosts: localhost
  connection: local
  vars_files:
    - env_variable
  tasks:
  - name: Create public IP address
    azure_rm_publicipaddress:
      resource_group: "{{ resource_group }}"
      allocation_method: Static
      name: "{{ worker_vm_name }}"
    register: result

  - name: Add the newly created instance
    local_action: lineinfile
                  dest="/home/cloud_user/ansible/Azure_Poc/hosts"
                  regexp={{ result.state.ip_address  }}
                  insertafter="[worker]" line={{ result.state.ip_address }}
    tags: test


  - name: Create virtual network inteface card
    azure_rm_networkinterface:
      resource_group: "{{ resource_group }}"
      name: "{{ worker_vm_name }}"
      virtual_network: "{{ virtual_network }}"
      subnet: "{{ master_vm_name }}"
      public_ip_name: "{{ worker_vm_name }}"
      security_group: "{{ master_vm_name }}"
    register: dns

  - name: add private IP
    lineinfile:
     path: /home/cloud_user/ansible/Azure_Poc/playbooks/env_variables
     regexp: "{{ dns.state.ip_configuration.private_ip_address }}"
     insertafter: 'check'
     line: "private_ip: {{dns.state.ip_configuration.private_ip_address}}"

  - name: Adding DNS name
    lineinfile:
      path: /home/cloud_user/ansible/Azure_Poc/playbooks/env_variables
      insertafter: "check"
      line: "worker: worker-node"
      state: present

  - name: Create VM
    azure_rm_virtualmachine:
      resource_group: "{{ resource_group }}"
      name: "{{ worker_vm_name }}"
      vm_size: Standard_D2s_v3
      admin_username: serosoft
      admin_password: serosoft@123
      network_interfaces: "{{ worker_vm_name }}"
      image:
        publisher: OpenLogic
        sku: 7.5
        version: latest
        offer: CentOS
    register: vm
    tags: test
