---
- name: test
  hosts: localhost
  tasks:
  - name: Tag and push to local registry
    docker_image:
      # Image will be centos:7
      name: tomcat
      # Will be pushed to localhost:5000/centos:7
      repository: 15.206.158.170:5000/tomcat
      tag: mayur
      push: yes
      source: local

# This file needs update
